definitions:
  environment: &env
    flutter: stable
    xcode: latest
    cocoapods: default
  
  # Caching configuration
  cache: &cache
    cache_paths:
      - $HOME/.pub-cache
      - $FCI_BUILD_DIR/.dart_tool
      - $HOME/Library/Caches/CocoaPods

workflows:
  # ============================================
  # iOS Production Build
  # ============================================
  # ============================================
  # iOS Production Build (Unsigned)
  # ============================================
  ios-production:
    name: iOS Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      <<: *env
      vars:
        FLUTTER_FLAVOR: production
    <<: *cache
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS App (Unsigned)
        script: |
          flutter build ios \
            --release \
            --no-codesign \
            --flavor production
      
      - name: Package Payload to IPA
        script: |
          # Find the .app in the build directory (handling flavors)
          APP_PATH=$(find build/ios -name "*.app" -type d | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "No .app found in build/ios!"
            ls -R build/ios
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          
          # Prepare Payload
          rm -rf Payload
          mkdir Payload
          cp -r "$APP_PATH" Payload/
          
          # Zip into IPA
          zip -r -y kebap.ipa Payload
          
          echo "IPA created at: $(pwd)/kebap.ipa"
          ls -lh kebap.ipa
    
    artifacts:
      - kebap.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - $CM_EMAIL
        notify:
          success: true
          failure: true

  # ============================================
  # macOS Production Build
  # ============================================
  macos-production:
    name: macOS Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      <<: *env
      vars:
        FLUTTER_FLAVOR: production
    <<: *cache
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd macos
          pod install --repo-update
      
      - name: Build macOS app
        script: |
          flutter build macos \
            --release \
            --no-codesign \
            --flavor production
      
      - name: Create DMG
        script: |
          # Find the .app in the build directory
          APP_PATH=$(find build/macos -name "*.app" -type d | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "No .app found in build/macos!"
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          
          DMG_NAME="Kebap.dmg"
          
          # Create DMG using hdiutil
          hdiutil create -volname "Kebap" -srcfolder "$APP_PATH" -ov -format UDZO "$DMG_NAME"
          
          echo "DMG created at: $(pwd)/$DMG_NAME"
          ls -lh "$DMG_NAME"
    
    artifacts:
      - Kebap.dmg
    
    publishing:
      email:
        recipients:
          - $CM_EMAIL
        notify:
          success: true
          failure: true

  # ============================================
  # iOS Development Build (optional)
  # ============================================
  # ============================================
  # iOS Development Build (Unsigned)
  # ============================================
  ios-development:
    name: iOS Development
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      <<: *env
      vars:
        FLUTTER_FLAVOR: development
    <<: *cache
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS App (Unsigned)
        script: |
          flutter build ios \
            --release \
            --no-codesign \
            --flavor development
      
      - name: Package Payload to IPA
        script: |
          # Find the .app in the build directory
          APP_PATH=$(find build/ios -name "*.app" -type d | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "No .app found!"
            exit 1
          fi
          echo "Found app at: $APP_PATH"
          
          rm -rf Payload
          mkdir Payload
          cp -r "$APP_PATH" Payload/
          
          zip -r -y kebap_dev.ipa Payload
          
          echo "IPA created at: $(pwd)/kebap_dev.ipa"
          ls -lh kebap_dev.ipa
    
    artifacts:
      - kebap_dev.ipa    
    publishing:
      email:
        recipients:
          - $CM_EMAIL
        notify:
          success: true
          failure: true