definitions:
  environment: &env
    flutter: stable
    xcode: latest
    cocoapods: default
  
  # Caching configuration
  cache: &cache
    cache_paths:
      - $HOME/.pub-cache
      - $FCI_BUILD_DIR/.dart_tool
      - $HOME/Library/Caches/CocoaPods

workflows:
  # ============================================
  # iOS Production Build
  # ============================================
  # ============================================
  # iOS Production Build (Unsigned)
  # ============================================
  ios-production:
    name: iOS Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      <<: *env
      vars:
        FLUTTER_FLAVOR: production
    <<: *cache
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS App (Unsigned)
        script: |
          flutter build ios \
            --release \
            --no-codesign \
            --flavor production
      
      - name: Package Payload to IPA
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r kebap.ipa Payload
    
    artifacts:
      - build/ios/iphoneos/kebap.ipa
      - /tmp/xcodebuild_logs/*.log

  # ============================================
  # macOS Production Build
  # ============================================
  macos-production:
    name: macOS Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      <<: *env
      vars:
        FLUTTER_FLAVOR: production
    <<: *cache
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd macos
          pod install --repo-update
      
      - name: Build macOS app
        script: |
          flutter build macos \
            --release \
            --no-codesign \
            --flavor production
      
      - name: Create DMG
        script: |
          cd build/macos/Build/Products/Release-production
          APP_NAME=$(ls -d *.app | head -1)
          DMG_NAME="${APP_NAME%.app}.dmg"
          hdiutil create -volname "Kebap" -srcfolder "$APP_NAME" -ov -format UDZO "$DMG_NAME"
    
    artifacts:
      - build/macos/Build/Products/Release-production/*.app
      - build/macos/Build/Products/Release-production/*.dmg

  # ============================================
  # iOS Development Build (optional)
  # ============================================
  # ============================================
  # iOS Development Build (Unsigned)
  # ============================================
  ios-development:
    name: iOS Development
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      <<: *env
      vars:
        FLUTTER_FLAVOR: development
    <<: *cache
    
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      
      - name: Build iOS App (Unsigned)
        script: |
          flutter build ios \
            --release \
            --no-codesign \
            --flavor development
      
      - name: Package Payload to IPA
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r kebap_dev.ipa Payload
    
    artifacts:
      - build/ios/iphoneos/kebap_dev.ipa
