FROM ghcr.io/nginxinc/nginx-unprivileged:stable-alpine-slim

EXPOSE 8080

ENV BASE_URL=""

COPY build/web /usr/share/nginx/html

RUN echo '{"baseUrl": "${BASE_URL}"}' > /usr/share/nginx/html/assets/config/config.json

CMD /bin/sh -c 'sed -i s/80/8080/g /etc/nginx/conf.d/default.conf && sed -i "s|\${BASE_URL}|${BASE_URL}|g" /usr/share/nginx/html/assets/config/config.json && nginx -g "daemon off;"'
